[project]
name = "hdrUtils"
version = "0.1.0"
description = "Package description for hdrUtils"
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = { text = "MIT" }
project.authors = [
  { name = "Suhail", email = "suhailece@gmail.com" },
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Original [tool.poetry] has been migrated to PEP 621 by migrate2uv.sh
